### ISSUE TITLE
Inserer un tableau comparatif

### ISSUE THREAD

**Issue by simple-acces** [simple-acces/simple-acces-website#18]
J'aurai besoin d'insérer un tableau comparatif des offres avec au moins 9 lignes et 3 colonnes. Il y aurait moyen d'utiliser le plugin grid et de le customiser pour avoir des traits, des fonds,... (un peu comme els pluggins qu'on trouve sur WP)?

**Comment by RonanDrouglazet** [comment]
je t'ai mis un tableau à la place des deux offres actuelles (tu pourras toujours récupérer le contenu sur le site live)

j'ai mis un tableau "basic" qu'on pourras customiser ensemble.
tu peux aller voir les quelques options que bootstrap propose, genre bordered table, ou hovered table (on peux les combiner)
https://getbootstrap.com/docs/4.0/content/tables/

on pourra changer background / type de bordure (pointiller / continu / epaisseur / etc..)

tu peux dors et déjà remplir le tableau avec le contenu et on pourra modifier son style par la suite ensemble
